common: &default_settings
  license_key: <%= ENV.fetch("NEWRELIC_LICENSE_KEY") %>
  app_name: 'newthink_market_api'
production:
  <<: *default_settings
  log_level: info
development:
  <<: *default_settings
  log_level: debug